name: firebase_flow
description: Dart package which manages the authentication domain.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: ../cache
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  equatable: ^2.0.5
  google_sign_in: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.2