name: user_repository
description: Dart package which manages the user domain.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  uuid: ^3.0.6
  flutter_lints: ^2.0.0